#!/usr/bin/env ruby

require 'json'

filename = ARGV[0]

best_solution = { "score" => 999.0 }
line_count = 0
File.readlines(filename).each { |line|
    line_count += 1

    result = `./xor_cipher_decode #{line}`
    next if result.empty?

    result = result.split("\n")

    current_score = result[1].to_f

    if current_score < best_solution["score"]
        best_solution = {
          "key" => result[0].to_i,
          "score" => result[1].to_f,
          "text" => result.slice(2..-1).join('\n')
        }
        best_solution["line"] = line_count
    end
}

puts best_solution.to_json
