#!/usr/bin/env ruby

require 'json'

filename = ARGV[0]

best_solution = { "score" => 9999 }
line_count = 0
File.readlines(filename).each { |line|
    line_count += 1

    result = `./xor_cipher_decode #{line}`
    next if result.empty?

    begin
      result = result.split("\n")
    rescue
      next
    end

    current_solution = Hash.new
    current_solution["key"] = result[0].to_i
    current_solution["score"] = result[1].to_f
    current_solution["text"] = result.slice(2..-1).join('\n')

    if current_solution["score"] < best_solution["score"]
        best_solution = current_solution
        best_solution["line"] = line_count
    end
}

puts best_solution.to_json
