name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make -C cryptopals/set1
      run: make -C cryptopals/set1
    - name: cd cryptopals/set1; ./run_test.sh
      run: cd cryptopals/set1; ./run_test.sh
    - name: make -C projecteuler
      run: make -C projecteuler
    - name: make -C projecteuler test_suite; ./projecteuler/test_suite
      run: make -C projecteuler test_suite; ./projecteuler/test_suite
    - name: install racket
      run: sudo add-apt-repository ppa:plt/racket && sudo apt-get update && sudo apt install drracket -y
