name: 'projecteuler'

on:
  push:
    branches: [ master ]
    paths:
    - 'projecteuler/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make -C projecteuler
      run: make -C projecteuler
